import SmoothScroll from 'global_components/SmoothScroll';
import CalculateAppHeight from 'global_components/layout/CalculateAppHeight';
import 'styles/App.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  // prevent zoom in on input focus
  viewport:
    'width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=no;user-scalable=0;',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CalculateAppHeight>
      <SmoothScroll>
        <html lang="en">
          <body>{children}</body>
        </html>
      </SmoothScroll>
    </CalculateAppHeight>
  );
}
